### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by yangton** [MoWafy001/YAML-To-Resume#1]
PS C:\Users\14859\Desktop\Resume-Creator-Script-main> python .\script.py
Traceback (most recent call last):
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\script.py", line 8, in <module>
    layout, file_name = engine.render()
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\src\TemplateEngine.py", line 143, in render
    return self.replace_blocks_with_html(), file_name
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\src\TemplateEngine.py", line 49, in replace_blocks_with_html
    html_lines = list(map(self.find_blocks_and_replace, html_lines))
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\src\TemplateEngine.py", line 63, in find_blocks_and_replace
    block_html = self.replace_blocks_with_html(block_html)
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\src\TemplateEngine.py", line 46, in replace_blocks_with_html
    html = self.find_list_and_dicts_and_replace(html)
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\src\TemplateEngine.py", line 102, in find_list_and_dicts_and_replace
    listordict = get_var(key)
  File "C:\Users\14859\Desktop\Resume-Creator-Script-main\src\vars_loader.py", line 8, in get_var
    raise Exception(f'Variable {var_name} not found')
Exception: Variable experience not found

**Comment by MoWafy001** [comment]
You got 
> Exception: Variable experience not found

because your **vars.yaml** file is missing the **experience** array.

It should look something like this:
```yaml
experience:
  - Position, Company:
    - start date - end date
    - |
      description
```

If, however, you don't want an experience section, you can remove the line **#experience#** from _layout/layout.html_


**Before**
```html
  <body>
    #header#
    <div class="content">
      #summary#
      #skills#
      #experience#
      #education#
    </div>
  </body>
```

**After**
```html
  <body>
    #header#
    <div class="content">
      #summary#
      #skills#
      #education#
    </div>
  </body>
```

**Comment by yangton** [comment]
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from src.TemplateEngine import TemplateEngine
ImportError: No module named src.TemplateEngine

**Comment by yangton** [comment]
idk

**Comment by MoWafy001** [comment]
Make sure the **src** directory and the files inside are not missing.

In the first comment you wrote, it looks like the files were imported with no error. You may have deleted something by mistake.

**Comment by yangton** [comment]
yangton@DESKTOP-6PINA0R:/mnt/c/Users/14859/Desktop/yangton cv$ python script.py
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from src.TemplateEngine import TemplateEngine
ImportError: No module named src.TemplateEngine
yangton@DESKTOP-6PINA0R:/mnt/c/Users/14859/Desktop/yangton cv$ python3 script.py
Traceback (most recent call last):
  File "script.py", line 8, in <module>
    layout, file_name = engine.render()
  File "/mnt/c/Users/14859/Desktop/yangton cv/src/TemplateEngine.py", line 143, in render
    return self.replace_blocks_with_html(), file_name
  File "/mnt/c/Users/14859/Desktop/yangton cv/src/TemplateEngine.py", line 49, in replace_blocks_with_html
    html_lines = list(map(self.find_blocks_and_replace, html_lines))
  File "/mnt/c/Users/14859/Desktop/yangton cv/src/TemplateEngine.py", line 63, in find_blocks_and_replace
    block_html = self.replace_blocks_with_html(block_html)
  File "/mnt/c/Users/14859/Desktop/yangton cv/src/TemplateEngine.py", line 46, in replace_blocks_with_html
    html = self.find_list_and_dicts_and_replace(html)
  File "/mnt/c/Users/14859/Desktop/yangton cv/src/TemplateEngine.py", line 102, in find_list_and_dicts_and_replace
    listordict = get_var(key)
  File "/mnt/c/Users/14859/Desktop/yangton cv/src/vars_loader.py", line 8, in get_var
    raise Exception(f'Variable {var_name} not found')
Exception: Variable education not found
yangton@DESKTOP-6PINA0R:/mnt/c/Users/14859/Desktop/yangton cv$

**Comment by yangton** [comment]
Just I don't know what it's going on xD

**Comment by yangton** [comment]
![image](https://user-images.githubusercontent.com/82059779/180077088-eb98be5b-f899-49a6-a4bd-3382f2600ecf.png)

**Comment by MoWafy001** [comment]
OK, this makes sense. 
### 1
You are using Ubuntu WSL. If you run `python script.py` you will be using python2 and not python3. This will cause an error. You will need to run `python3 script.py` instead.

### 2
If you read the last line it says  "Exception: Variable education not found". It is the same error you started the issue with, instead of experience, it's education. You will either add an **education** array to vars.yaml or remove **#education#** from layout/layout.html.

If you remove it though, you won't have much left in the resume...

You can check the **vars.yaml** in the repository, or read the **README** for reference.

**Comment by yangton** [comment]
cramp it works, but not quite

**Comment by yangton** [comment]
You could run it for me because it won't work for me, I guess
